metadata:
    org:
        id: "131"
        handle: kajendranalagaratnam
    displayName: greeter1
    displayType: ballerinaService
    description: ""
    version: 1.0.0
    projectId: 87a7990c-1099-4daf-b852-ecf3e1041fbf
    accessibility: external
    repository:
        appSubPath: greeter
        orgApp: kaje94
        nameApp: choreo-vscode-ext-test-7
        branchApp: main
        gitProvider: github
id: ""
handler: ""
commitHash: ""
