metadata:
    org:
        id: "3061"
        handle: kajendranalagaratnam
    displayName: greeter
    displayType: ballerinaService
    description: ""
    version: 1.0.0
    projectId: ""
    accessibility: external
    repository:
        appSubPath: greeter
        orgApp: kaje94
        nameApp: choreo-vscode-ext-test-7
        branchApp: main
        gitProvider: github
id: ""
handler: ""
commitHash: ""
