id: 2b57ea3b-4a32-44d5-a7ce-99d0d4a29f3c
orgId: 131
name: choreo-vscode-ext-test-7
version: 1.0.0
createdDate: ""
handler: ""
region: US
description: ""
repository: choreo-vscode-ext-test-7
branch: main
gitProvider: github
gitOrganization: kaje94
