id: f1eabb96-4e67-4466-97ac-e3f31479b9c2
GitOrganization: kaje94
GitProvider: github
Repository: choreo-vscode-ext-test-7
branch: main
description: ""
name: choreo-mono-repo-for-logs-test-3
orgId: 131
region: US
version: 1.0.0
